# Generated by Django 4.0.4 on 2022-04-26 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Subject code')),
                ('fname', models.CharField(max_length=50, verbose_name='Subject name')),
            ],
        ),
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Course type')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('email_addr', models.CharField(max_length=50)),
                ('reading_username', models.CharField(default='', max_length=30, unique=True)),
                ('pt_username', models.CharField(default='', max_length=30, unique=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ctkirep.coursetype')),
            ],
        ),
        migrations.CreateModel(
            name='ReadingTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(default='', max_length=50, verbose_name='Reading activity')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctkirep.student')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_order', models.SmallIntegerField(default=0, verbose_name='Subject order')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctkirep.coursesubject')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctkirep.coursetype')),
            ],
        ),
    ]
