# Generated by Django 4.0.4 on 2022-04-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctkirep', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingtime',
            name='duration',
            field=models.DurationField(verbose_name='Reading duration'),
        ),
        migrations.AlterField(
            model_name='readingtime',
            name='end',
            field=models.DateTimeField(verbose_name='End time'),
        ),
        migrations.AlterField(
            model_name='readingtime',
            name='start',
            field=models.DateTimeField(verbose_name='Start time'),
        ),
    ]
