# Generated by Django 4.0.4 on 2022-04-26 20:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctkirep', '0002_alter_readingtime_duration_alter_readingtime_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingTimeUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2022, 4, 26, 23, 54, 43, 717197))),
                ('file', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
