# Generated by Django 4.0.4 on 2022-04-28 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctkirep', '0003_readingtimeupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingtime',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='readingtimeupload',
            name='file',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='readingtimeupload',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
