# Generated by Django 4.0.4 on 2022-04-28 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctkirep', '0004_alter_readingtime_id_alter_readingtimeupload_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=50, verbose_name='Reading activity')),
            ],
        ),
    ]
