# Generated by Django 4.0.4 on 2022-04-28 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ctkirep', '0006_alter_readingactivity_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='ractivity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ctkirep.readingactivity'),
            preserve_default=False,
        ),
    ]
