# Generated by Django 4.0.4 on 2022-04-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctkirep', '0009_alter_readingactivity_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetype',
            name='sorder',
            field=models.SmallIntegerField(default=0, verbose_name='Order'),
        ),
    ]
