# Generated by Django 4.0.4 on 2022-04-30 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ctkirep', '0010_coursetype_sorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readingactivity',
            old_name='activity',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='readingtime',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='readingtime',
            name='username',
        ),
        migrations.AddField(
            model_name='readingtime',
            name='activity_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ctkirep.readingactivity', verbose_name='Activity ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='readingtime',
            name='student_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ctkirep.student', verbose_name='Student user ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='ractivity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ctkirep.readingactivity', verbose_name='Reading activity ID'),
        ),
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctkirep.coursesubject', verbose_name='Subject ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ctkirep.coursetype', verbose_name='Course ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email_addr',
            field=models.CharField(max_length=50, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='pt_username',
            field=models.CharField(default='', max_length=30, unique=True, verbose_name='ACE login'),
        ),
        migrations.AlterField(
            model_name='student',
            name='reading_username',
            field=models.CharField(default='', max_length=30, unique=True, verbose_name='iMRS login'),
        ),
        migrations.AlterField(
            model_name='student',
            name='surname',
            field=models.CharField(max_length=30, verbose_name='Surname'),
        ),
    ]
