# Generated by Django 4.0.4 on 2022-05-02 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctkirep', '0011_rename_activity_readingactivity_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readingtime',
            old_name='activity_id',
            new_name='activity',
        ),
        migrations.RenameField(
            model_name='readingtime',
            old_name='student_id',
            new_name='student',
        ),
    ]
