# Generated by Django 4.0.4 on 2022-05-02 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctkirep', '0012_rename_activity_id_readingtime_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='reqtime',
            field=models.DurationField(null=True, verbose_name='Required reading time'),
        ),
    ]
