# Generated by Django 4.0.4 on 2022-05-04 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ctkirep', '0014_aceactivity_acestatus_acecontentactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACEActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='ACEContentStatus',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Score')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctkirep.aceactivity', verbose_name='Activity')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctkirep.acestatus', verbose_name='Status')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctkirep.student', verbose_name='Student')),
            ],
        ),
        migrations.AddField(
            model_name='aceactivity',
            name='atype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ctkirep.aceactivitytype', verbose_name='Display type'),
        ),
    ]
