# Generated by Django 4.0.4 on 2022-05-06 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctkirep', '0015_aceactivitytype_acecontentstatus_aceactivity_atype'),
    ]

    operations = [
        migrations.CreateModel(
            name='PTUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='aceactivity',
            name='extref',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acecontentstatus',
            name='timestamp',
            field=models.DateTimeField(null=True, verbose_name='Timestamp'),
        ),
    ]
