# Generated by Django 4.0.4 on 2022-05-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctkirep', '0016_ptupload_aceactivity_extref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acecontentstatus',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Score'),
        ),
    ]
