# Generated by Django 4.0.4 on 2022-05-08 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ctkirep', '0017_alter_acecontentstatus_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='aceactivity',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ctkirep.coursesubject', verbose_name='Subject ID'),
            preserve_default=False,
        ),
    ]
