# Generated by Django 4.0.4 on 2022-05-08 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctkirep', '0018_aceactivity_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aceactivity',
            name='subject',
        ),
    ]
