# Generated by Django 4.0.4 on 2022-05-08 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ctkirep', '0019_remove_aceactivity_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='aceactivity',
            name='aorder',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aceactivity',
            name='subject',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='ctkirep.coursesubject', verbose_name='Subject ID'),
            preserve_default=False,
        ),
    ]
