# Generated by Django 4.0.4 on 2022-05-08 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctkirep', '0020_aceactivity_aorder_aceactivity_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aceactivity',
            old_name='aorder',
            new_name='ord',
        ),
    ]
