# Generated by Django 4.0.4 on 2022-05-08 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ctkirep', '0021_rename_aorder_aceactivity_ord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aceactivity',
            name='atype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctkirep.aceactivitytype', verbose_name='Display type'),
        ),
    ]
