# Generated by Django 4.0.4 on 2022-05-08 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctkirep', '0022_alter_aceactivity_atype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aceactivity',
            name='atype',
        ),
        migrations.RemoveField(
            model_name='aceactivity',
            name='ord',
        ),
        migrations.RemoveField(
            model_name='aceactivity',
            name='subject',
        ),
    ]
