# Generated by Django 4.0.4 on 2022-05-08 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ctkirep', '0023_remove_aceactivity_atype_remove_aceactivity_ord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aceactivity',
            name='atype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ctkirep.aceactivitytype', verbose_name='Display type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aceactivity',
            name='ord',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aceactivity',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ctkirep.coursesubject', verbose_name='Subject ID'),
            preserve_default=False,
        ),
    ]
