# Generated by Django 4.0.4 on 2022-05-08 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctkirep', '0024_aceactivity_atype_aceactivity_ord_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acecontentstatus',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='ACEContentActivity',
        ),
    ]
