# Generated by Django 4.0.4 on 2022-05-08 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ctkirep', '0025_alter_acecontentstatus_id_delete_acecontentactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACEAction',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='acestatus',
            name='id',
            field=models.SmallAutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='ACELearnerJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp')),
                ('duration', models.DurationField(verbose_name='Reading duration')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Score')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctkirep.aceaction', verbose_name='Action')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctkirep.aceactivity', verbose_name='Activity')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctkirep.student', verbose_name='Student')),
            ],
        ),
    ]
