# Generated by Django 4.0.4 on 2022-05-10 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ctkirep', '0028_alter_acelearnerjourney_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='acelearnerjourney',
            name='response',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acelearnerjourney',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctkirep.acestatus', verbose_name='Action'),
        ),
        migrations.DeleteModel(
            name='ACEAction',
        ),
    ]
