# Generated by Django 4.0.4 on 2022-05-31 18:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctkirep', '0029_acelearnerjourney_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetype',
            name='remote',
            field=models.BooleanField(default=False, verbose_name='Remote course'),
        ),
        migrations.AddField(
            model_name='student',
            name='start_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Course start date'),
        ),
    ]
