# Generated by Django 4.0.4 on 2022-06-07 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctkirep', '0030_coursetype_remote_student_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acecontentstatus',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
