# Generated by Django 4.0.4 on 2022-06-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctkirep', '0031_alter_acecontentstatus_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acecontentstatus',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
