# Generated by Django 4.0.4 on 2022-06-10 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctkirep', '0033_alter_coursesubject_fname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acelearnerjourney',
            name='response',
            field=models.TextField(),
        ),
    ]
